export default function({ app, redirect, route }) {
	// Checking if user is logged in...
	if (!app.$auth.loggedIn) return redirect('/login');
	// Getting the user...
	const user = app.$auth.user;
	// Redirecting user to home page if user got nothing to do i.e. no permissions...
	if (!user.permissions.length && route.path !== '/dashboard/me') return redirect('/');
	// Redirecting to base dashboard page if path is of super-admin and no permissions is available...
	if (route.path === '/dashboard/super-admin' && !user.permissions.find(perms => perms.instituteId === null)) return redirect('/dashboard');
	// Getting the id from query...
	const { id } = route.query;
	// Redirecting user to dashboard page if user doesn't have any permissions for the provided institute id...
	if (id && !user.permissions.filter(perms => perms.instituteId === id).length) return redirect('/dashboard');
}
